-- migrate:up
ALTER TABLE projects ADD COLUMN backlog INTEGER NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN todo INTEGER NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN done INTEGER NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN completed INTEGER NOT NULL DEFAULT 0;

-- migrate:down
ALTER TABLE projects DROP COLUMN backlog;
ALTER TABLE projects DROP COLUMN todo;
ALTER TABLE projects DROP COLUMN done;
ALTER TABLE projects DROP COLUMN completed;
