package migrate

import (
	"os"
	"path/filepath"
	"slices"
	"testing"

	"github.com/B4Dmonkey/bit-pro/task"
)

func TestUnknownFiles(t *testing.T) {
	tests := []struct {
		name  string
		files []string
		dirs  []string
		want  []string
	}{
		{
			name: "every known shape",
			files: []string{
				"config.toml",
				"tasks/BIT-1.md",
				"completed/BIT-2.md",
				"archive/tasks/BIT-3.md",
				"feedback/BIT-1-001.md",
				"research/BIT-1/index.md",
				"retro/album-proposals.md",
			},
		},
		{
			name:  "research too deep",
			files: []string{"research/BIT-1/sub/x.md"},
			want:  []string{"research/BIT-1/sub/x.md"},
		},
		{
			name:  "research file at the top",
			files: []string{"research/index.md"},
			want:  []string{"research/index.md"},
		},
		{
			name:  "feedback with no seq",
			files: []string{"feedback/notes.md"},
			want:  []string{"feedback/notes.md"},
		},
		{
			name:  "retro without proposals",
			files: []string{"retro/summary.md"},
			want:  []string{"retro/summary.md"},
		},
		{
			name:  "flat archive",
			files: []string{"archive/BIT-3.md"},
			want:  []string{"archive/BIT-3.md"},
		},
		{
			name:  "non-md in a task dir",
			files: []string{"tasks/BIT-1.txt"},
			want:  []string{"tasks/BIT-1.txt"},
		},
		{
			name:  "dotfiles",
			files: []string{".DS_Store", "tasks/.DS_Store"},
			want:  []string{".DS_Store", "tasks/.DS_Store"},
		},
		{
			name: "empty completed dir",
			dirs: []string{"completed"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			src := t.TempDir()

			for _, d := range tt.dirs {
				if err := os.MkdirAll(filepath.Join(src, d), 0o755); err != nil {
					t.Fatalf("os.MkdirAll(%q) returned error: %v", d, err)
				}
			}

			for _, f := range tt.files {
				path := filepath.Join(src, filepath.FromSlash(f))
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					t.Fatalf("os.MkdirAll(%q) returned error: %v", filepath.Dir(path), err)
				}

				if err := os.WriteFile(path, []byte("x\n"), 0o600); err != nil {
					t.Fatalf("os.WriteFile(%q) returned error: %v", path, err)
				}
			}

			got, err := unknownFiles(src)
			if err != nil {
				t.Fatalf("unknownFiles() returned error: %v", err)
			}

			if !slices.Equal(got, tt.want) {
				t.Errorf("unknownFiles() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestBadTaskFiles(t *testing.T) {
	good, err := (&task.Task{ID: "BIT-1", Title: "Good", Status: task.StatusTodo, Body: "body\n"}).Bytes()
	if err != nil {
		t.Fatalf("Bytes() returned error: %v", err)
	}

	tests := []struct {
		name string
		data string
		want []string
	}{
		{
			name: "generated by Bytes",
			data: string(good),
		},
		{
			name: "missing closing delimiter",
			data: "---\nid: BIT-1\ntitle: Good\nstatus: todo\n",
			want: []string{"tasks/BIT-1.md: task file missing closing frontmatter delimiter"},
		},
		{
			name: "keys out of order",
			data: "---\ntitle: Good\nid: BIT-1\nstatus: todo\n---\nbody\n",
			want: []string{"tasks/BIT-1.md: does not round-trip"},
		},
		{
			name: "lowercase order entries",
			data: "---\nid: BIT-1\ntitle: Good\nstatus: todo\norder:\n    - bit-1.1\n---\nbody\n",
		},
		{
			name: "lowercase id",
			data: "---\nid: bit-1\ntitle: Good\nstatus: todo\n---\nbody\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			src := t.TempDir()
			path := filepath.Join(src, "tasks", "BIT-1.md")

			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				t.Fatalf("os.MkdirAll(%q) returned error: %v", filepath.Dir(path), err)
			}

			if err := os.WriteFile(path, []byte(tt.data), 0o600); err != nil {
				t.Fatalf("os.WriteFile(%q) returned error: %v", path, err)
			}

			got, err := badTaskFiles(src)
			if err != nil {
				t.Fatalf("badTaskFiles() returned error: %v", err)
			}

			if !slices.Equal(got, tt.want) {
				t.Errorf("badTaskFiles() = %v, want %v", got, tt.want)
			}
		})
	}
}

const upperPrefix = "BIT"

func TestBadIDs(t *testing.T) {
	tests := []struct {
		name   string
		prefix string
		files  []string
		want   []string
	}{
		{
			name:   "lowercase prefix",
			prefix: "bit",
			want:   []string{"config.toml: bit"},
		},
		{
			name:   "lowercase feedback track",
			prefix: upperPrefix,
			files:  []string{"feedback/bit-1-001.md"},
			want:   []string{"feedback/bit-1-001.md: bit-1"},
		},
		{
			name:   "lowercase research dir",
			prefix: upperPrefix,
			files:  []string{"research/bit-1/index.md"},
			want:   []string{"research/bit-1: bit-1"},
		},
		{
			name:   "uppercase store",
			prefix: upperPrefix,
			files: []string{
				"feedback/BIT-1-001.md",
				"research/BIT-1/index.md",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			src := t.TempDir()

			for _, f := range tt.files {
				path := filepath.Join(src, filepath.FromSlash(f))
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					t.Fatalf("os.MkdirAll(%q) returned error: %v", filepath.Dir(path), err)
				}

				if err := os.WriteFile(path, []byte("x\n"), 0o600); err != nil {
					t.Fatalf("os.WriteFile(%q) returned error: %v", path, err)
				}
			}

			if got := badIDs(src, tt.prefix); !slices.Equal(got, tt.want) {
				t.Errorf("badIDs() = %v, want %v", got, tt.want)
			}
		})
	}
}
